# tag::system[]
apiVersion: apps.openliberty.io/v1
# tag::olappSys[]
kind: OpenLibertyApplication
# end::olappSys[]
metadata:
  name: system
spec:
  # tag::sysImage[]
  applicationImage: [registry-name].azurecr.io/system:1.0-SNAPSHOT
  # end::sysImage[]
  # tag::createKNativeSys[]
  createKnativeService: true
  # end::createKNativeSys[]
  # tag::service[]
  service:
    # tag::sysLoadBalancer[]
    type: LoadBalancer
    # end::sysLoadBalancer[]
    port: 9080
    targetPort: 9080
  # end::service[]
  pullPolicy: Always
  manageTLS: false
  # tag::exposeSystem[]
  expose: true
  # end::exposeSystem[]
  # tag:sysSecret[]
  pullSecret: guidesecret
  # end:sysSecret[]
  # tag::securityContextSys[]
  securityContext:
    # tag::runAsNonRoot[]
    runAsNonRoot: true
    # end::runAsNonRoot[]
    privileged: false
    allowPrivilegeEscalation: true
    # tag::capabilities[]
    capabilities:
      add:
      - CHECKPOINT_RESTORE
      - SETPCAP
      drop:
      - ALL
    # end::capabilities[]
  # end::securityContextSys[]
  # tag::semeruCloudCompilerSys[]
  semeruCloudCompiler:
    # tag::enable[]
    enable: true
    # end::enable[]
    replicas: 3
  # end::semeruCloudCompilerSys[]
# end::system[]
---
# tag::inventory[]
apiVersion: apps.openliberty.io/v1
# tag::olapp[]
kind: OpenLibertyApplication
# end::olapp[]
metadata:
  name: inventory
spec:
  # tag::invImage[]
  applicationImage: [registry-name].azurecr.io/inventory:1.0-SNAPSHOT
  # end::invImage[]
  # tag::createKNativeInv[]
  createKnativeService: true
  # end::createKNativeInv[]
  # tag::service[]
  service:
    # tag::invLoadBalancer[]
    type: LoadBalancer
    # end::invLoadBalancer[]
    port: 9081
    targetPort: 9081
  # end::service[]
  pullPolicy: Always
  manageTLS: false
  # tag::exposeInv[]
  expose: true
  # end::exposeInv[]
  # tag:invSecret[]
  pullSecret: guidesecret
  # end:invSecret[]
  # tag::securityContextInv[]
  securityContext:
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - CHECKPOINT_RESTORE
      - SETPCAP
      drop:
      - ALL
  # end::securityContextInv[]
  # tag::semeruCloudCompilerInv[]
  semeruCloudCompiler:
    enable: true
    replicas: 3
  # end::semeruCloudCompilerInv[]
  env:
  - name: system.http.port
    value: "80"
# end::inventory[]