# tag::system[]
apiVersion: apps.openliberty.io/v1
# tag::olappSystem[]
kind: OpenLibertyApplication
# end::olappSystem[]
metadata:
  name: system
spec:
  # tag::sysImage[]
  applicationImage: [registry-name].azurecr.io/system:1.0-SNAPSHOT
  # end::sysImage[]
  # tag::createKNativeSystem[]
  createKnativeService: true
  # end::createKNativeSystem[]
  # tag::service[]
  service:
    type: LoadBalancer
    port: 9080
    targetPort: 9080
  # end::service[]
  pullPolicy: Always
  manageTLS: false
  # tag::exposeSystem[]
  expose: true
  # end::exposeSystem[]
  pullSecret: guidesecret
  # tag::securityContextSystem[]
  securityContext:
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - CHECKPOINT_RESTORE
      - SETPCAP
      drop:
      - ALL
  # end::securityContextSystem[]
  # tag::semeruCloudCompilerSystem[]
  semeruCloudCompiler:
    enable: true
    replicas: 3
  # end::semeruCloudCompilerSystem[]
# end::system[]
---
# tag::inventory[]
apiVersion: apps.openliberty.io/v1
# tag::olapp[]
kind: OpenLibertyApplication
# end::olapp[]
metadata:
  name: inventory
spec:
  # tag::sysImage[]
  applicationImage: [registry-name].azurecr.io/inventory:1.0-SNAPSHOT
  # end::sysImage[]
  # tag::createKNative[]
  createKnativeService: true
  # end::createKNative[]
  # tag::service[]
  service:
    type: LoadBalancer
    port: 9081
    targetPort: 9081
  # end::service[]
  pullPolicy: Always
  manageTLS: false
  # tag::expose[]
  expose: true
  # end::expose[]
  pullSecret: guidesecret
  # tag::securityContext[]
  securityContext:
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - CHECKPOINT_RESTORE
      - SETPCAP
      drop:
      - ALL
  # end::securityContext[]
  # tag::semeruCloudCompiler[]
  semeruCloudCompiler:
    enable: true
    replicas: 3
  # end::semeruCloudCompiler[]
  env:
  - name: system.http.port
    value: "80"

